export const products = [
  {
    id: 1,
    name: 'กระเป๋าเป้สายแฟชั่น',
    category: 'แฟชั่น',
    price: 490,
    originalPrice: 690,
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=700&q=80',
    description: 'กระเป๋าเป้ดีไซน์สวย เหมาะสำหรับใช้งานทุกวัน',
    rating: 4.8,
    sold: 1240,
    badge: 'ขายดี',
    shipping: 'ส่งฟรี',
  },
  {
    id: 2,
    name: 'หูฟังไร้สาย',
    category: 'อิเล็กทรอนิกส์',
    price: 1290,
    originalPrice: 1590,
    image: 'https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&w=700&q=80',
    description: 'เสียงคมชัด พร้อมแบตเตอรี่ใช้งานนาน',
    rating: 4.9,
    sold: 980,
    badge: 'แนะนำ',
    shipping: 'ส่งฟรี',
  },
  {
    id: 3,
    name: 'นาฬิกาข้อมือสปอร์ต',
    category: 'กีฬา',
    price: 860,
    originalPrice: 1120,
    image: 'https://images.unsplash.com/photo-1519241047957-be31d7379a5d?auto=format&fit=crop&w=700&q=80',
    description: 'นาฬิกาเท่ ๆ สำหรับชีวิต Active',
    rating: 4.7,
    sold: 760,
    badge: 'ลดแรง',
    shipping: 'ส่งฟรี',
  },
  {
    id: 4,
    name: 'ชุดทำความสะอาดบ้าน',
    category: 'ไลฟ์สไตล์',
    price: 560,
    originalPrice: 780,
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=700&q=80',
    description: 'อุปกรณ์ครบชุดเพื่อการทำความสะอาดได้ง่าย',
    rating: 4.6,
    sold: 540,
    badge: 'ใหม่',
    shipping: 'ส่งฟรี',
  },
  {
    id: 5,
    name: 'รองเท้าวิ่งเพื่อสุขภาพ',
    category: 'กีฬา',
    price: 1490,
    originalPrice: 1890,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',
    description: 'รองเท้ารองรับแรงกระแทกสำหรับการวิ่งระยะสั้น',
    rating: 4.8,
    sold: 640,
    badge: 'ยอดนิยม',
    shipping: 'ส่งฟรี',
  },
  {
    id: 6,
    name: 'แก้วน้ำเก็บความเย็น',
    category: 'ไลฟ์สไตล์',
    price: 340,
    originalPrice: 450,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=700&q=80',
    description: 'แก้วน้ำเย็นนาน เหมาะสำหรับพกพา',
    rating: 4.5,
    sold: 430,
    badge: 'มาใหม่',
    shipping: 'ส่งฟรี',
  },
];
